{% set name = "aoo-mozilla-en-dict" %}
{% set version = "2022-08-01" %}

package:
  name: {{ name }}
  version: {{ version.replace("-", ".") }}

source:
  url: https://github.com/marcoagpinto/{{ name }}/archive/{{ version }}gb.tar.gz
  sha256: 9abdd8adc9a0dc62c8f0a44a10264dbe1ec2bbf6a3916884476c674c6fe030d9

build:
  number: 1
  noarch: generic
  ignore_run_exports:
    - python

requirements:
  build:
    - python >=3.6

outputs:
  - name: hunspell-en
    build:
      noarch: generic
      ignore_run_exports:
        - python
    requirements:
      run:
        - hunspell
        - {{ name }}-au
        - {{ name }}-ca
        - {{ name }}-gb
        - {{ name }}-us
        - {{ name }}-za
    test:
      requires:
        - hunspell
        - python >=3.6
      commands:
        - cd {{ RECIPE_DIR }} && python hunspell_test.py

  - name: {{ name }}-au
    build:
      noarch: generic
      ignore_run_exports:
        - python
    script: copy_files.py
    about:
      license: MIT
      license_file: README_en_AU.txt
    test:
      requires:
        - hunspell
        - python >=3.6
      commands:
        - cd {{ RECIPE_DIR }} && python hunspell_test.py

  - name: {{ name }}-ca
    build:
      noarch: generic
      ignore_run_exports:
        - python
    script: copy_files.py
    about:
      license: MIT
      license_file: README_en_CA.txt
    test:
      requires:
        - hunspell
        - python >=3.6
      commands:
        - cd {{ RECIPE_DIR }} && python hunspell_test.py

  - name: {{ name }}-gb
    build:
      noarch: generic
      ignore_run_exports:
        - python
    script: copy_files.py
    about:
      license: LGPL-3.0-or-later
      license_file: README_en_GB.txt
    test:
      requires:
        - hunspell
        - python >=3.6
      commands:
        - cd {{ RECIPE_DIR }} && python hunspell_test.py

  - name: {{ name }}-us
    build:
      noarch: generic
    script: copy_files.py
    about:
      license: MIT
      license_file: README_en_US.txt
    test:
      requires:
        - hunspell
        - python >=3.6
      commands:
        - cd {{ RECIPE_DIR }} && python hunspell_test.py

  - name: {{ name }}-za
    build:
      noarch: generic
      ignore_run_exports:
        - python
    script: copy_files.py
    about:
      license: LGPL-3.0-or-later
      license_file: README_en_ZA.txt
    test:
      requires:
        - hunspell
        - python >=3.6
      commands:
        - cd {{ RECIPE_DIR }} && python hunspell_test.py

about:
  home: https://github.com/marcoagpinto/aoo-mozilla-en-dict
  summary: 'English Dictionaries Project (AOO+Mozilla+others)'
  license: LGPL-3.0-or-later
  license_file: README_en_GB.txt

extra:
  recipe-maintainers:
    - scopatz
    - bollwyvl
