{% set name = "aoo-mozilla-en-dict" %}
{% set version = "2020-06-01" %}

package:
  name: {{ name }}
  version: {{ version.replace("-", ".") }}

source:
  url: https://github.com/marcoagpinto/{{ name }}/archive/{{ version }}gb.tar.gz
  sha256: 02fca6f1d4218c37769fb10f87c30bc5e7cf49716fa07b592874a9ef1edb4f72

build:
  number: 2
  noarch: generic

requirements:
  build:
    - python >=3.6

outputs:
  - name: hunspell-en
    build:
      noarch: generic
    requirements:
      run:
        - hunspell
        - {{ name }}-au
        - {{ name }}-ca
        - {{ name }}-gb
        - {{ name }}-us
        - {{ name }}-za
    test:
      requires:
        - hunspell
        - python >=3.6
      commands:
        - cd {{ RECIPE_DIR }} && python hunspell_test.py

  - name: {{ name }}-au
    build:
      noarch: generic
    script: copy_files.py
    about:
      license: MIT
      license_file: README_en_AU.txt
    test:
      requires:
        - hunspell
        - python >=3.6
      commands:
        - cd {{ RECIPE_DIR }} && python hunspell_test.py

  - name: {{ name }}-ca
    build:
      noarch: generic
    script: copy_files.py
    about:
      license: MIT
      license_file: README_en_CA.txt
    test:
      requires:
        - hunspell
        - python >=3.6
      commands:
        - cd {{ RECIPE_DIR }} && python hunspell_test.py

  - name: {{ name }}-gb
    build:
      noarch: generic
    script: copy_files.py
    about:
      license: LGPL-3.0-or-later
      license_file: README_en_GB.txt
    test:
      requires:
        - hunspell
        - python >=3.6
      commands:
        - cd {{ RECIPE_DIR }} && python hunspell_test.py

  - name: {{ name }}-us
    build:
      noarch: generic
    script: copy_files.py
    about:
      license: MIT
      license_file: README_en_US.txt
    test:
      requires:
        - hunspell
        - python >=3.6
      commands:
        - cd {{ RECIPE_DIR }} && python hunspell_test.py

  - name: {{ name }}-za
    build:
      noarch: generic
    script: copy_files.py
    about:
      license: LGPL-3.0-or-later
      license_file: README_en_ZA.txt
    test:
      requires:
        - hunspell
        - python >=3.6
      commands:
        - cd {{ RECIPE_DIR }} && python hunspell_test.py

about:
  home: https://github.com/marcoagpinto/aoo-mozilla-en-dict
  summary: 'English Dictionaries Project (AOO+Mozilla+others)'
  license: LGPL-3.0-or-later
  license_file: README_en_GB.txt

extra:
  recipe-maintainers:
    - scopatz
    - bollwyvl
