{% set version = "2023-01-01" %}

package:
  name: aoo-mozilla-en-dict
  version: {{ version.replace("-", ".") }}

source:
  url: https://github.com/marcoagpinto/aoo-mozilla-en-dict/archive/{{ version }}gb.tar.gz
  sha256: 2a105ee49030fd8723efcd74f44f3f1eceed2968f7255d17ad35b5aafa8b5f71

build:
  number: 0
  noarch: generic
  merge_build_host: False

requirements:
  build:
    - python >=3.6
  host: []

outputs:
  - name: hunspell-en
    build: &build
      noarch: generic
    requirements:
      run:
        - hunspell
        - aoo-mozilla-en-dict-au
        - aoo-mozilla-en-dict-ca
        - aoo-mozilla-en-dict-gb
        - aoo-mozilla-en-dict-us
        - aoo-mozilla-en-dict-za
    test: &test
      files:
        - test_hunspell.py
      requires:
        - hunspell
        - pytest
        - python >=3.6
      commands:
        - pytest -vv -s test_hunspell.py

  - name: aoo-mozilla-en-dict-au
    build: *build
    script: copy_files.py
    test: *test
    about:
      license: MIT
      license_file: en_AU (Kevin Atkinson)/README_en_AU.txt

  - name: aoo-mozilla-en-dict-ca
    build: *build
    script: copy_files.py
    test: *test
    about:
      license: MIT
      license_file: en_CA (Kevin Atkinson)/README_en_CA.txt

  - name: aoo-mozilla-en-dict-gb
    build: *build
    script: copy_files.py
    about:
      license: LGPL-3.0-or-later
      license_file: en_GB (Marco Pinto)/README_en_GB.txt
    test: *test

  - name: aoo-mozilla-en-dict-us
    build: *build
    script: copy_files.py
    about:
      license: MIT
      license_file: en_US (Kevin Atkinson)/README_en_US.txt
    test: *test

  - name: aoo-mozilla-en-dict-za
    build: *build
    script: copy_files.py
    about:
      license: LGPL-3.0-or-later
      license_file: en_ZA (Dwayne Bailey)/README_en_ZA.txt
    test: *test

about:
  home: https://github.com/marcoagpinto/aoo-mozilla-en-dict
  summary: 'English Dictionaries Project (AOO+Mozilla+others)'
  license: LGPL-3.0-or-later
  license_file: README.md

extra:
  feedstock-name: hunspell-en
  recipe-maintainers:
    - scopatz
    - bollwyvl
