{% set version = "2024.03.01" %}

package:
  name: aoo-mozilla-en-dict
  version: {{ version }}

source:
  url: https://extensions.libreoffice.org/assets/downloads/41/1709273668/dict-en-{{ version.replace(".", "") }}_lo.oxt
  sha256: dd8e4fb6550ff5d84ff8dee48ef9b36868202691b19e014cd6271a2e0030aec1
  # oxt filetype is a wrapper around zip
  fn: dict-en-{{ version.replace(".", "") }}_lo.zip

build:
  number: 1
  noarch: generic
  merge_build_host: False
  ignore_run_exports:
    - python
    - python_abi

requirements:
  build:
    - python >=3.6
  host: []

outputs:
  - name: hunspell-en
    build: &build
      noarch: generic
    requirements:
      run:
        - hunspell
        - aoo-mozilla-en-dict-au
        - aoo-mozilla-en-dict-ca
        - aoo-mozilla-en-dict-gb
        - aoo-mozilla-en-dict-us
        - aoo-mozilla-en-dict-za
    test: &test
      files:
        - test_hunspell.py
      requires:
        - hunspell
        - pytest
        - python >=3.6
      commands:
        - python test_hunspell.py

  - name: aoo-mozilla-en-dict-au
    build: *build
    script: copy_files.py
    test: *test
    about:
      license: MIT
      license_file: README_en_AU.txt

  - name: aoo-mozilla-en-dict-ca
    build: *build
    script: copy_files.py
    test: *test
    about:
      license: MIT
      license_file: README_en_CA.txt

  - name: aoo-mozilla-en-dict-gb
    build: *build
    script: copy_files.py
    about:
      license: LGPL-3.0-or-later
      license_file: README_en_GB.txt
    test: *test

  - name: aoo-mozilla-en-dict-us
    build: *build
    script: copy_files.py
    about:
      license: MIT
      license_file: README_en_US.txt
    test: *test

  - name: aoo-mozilla-en-dict-za
    build: *build
    script: copy_files.py
    about:
      license: LGPL-3.0-or-later
      license_file: README_en_ZA.txt
    test: *test

about:
  home: https://extensions.libreoffice.org/en/extensions/show/english-dictionaries
  summary: 'English Dictionaries Project (AOO+Mozilla+others)'
  license: LGPL-3.0-or-later
  license_file: lgpl-3.0.txt

extra:
  feedstock-name: hunspell-en
  recipe-maintainers:
    - scopatz
    - bollwyvl
